### ISSUE TITLE
数据管理DMS服务器列表中没有查询到符合条件的服务器

### ISSUE THREAD

**Issue by byr1223** [zhouaini528/scientific_internet_access#13]
五：创建实例成功后点击“数据管理DMS”服务器列表中没有一台服务器，是什么问题？要怎么解决？

**Comment by zhouaini528** [comment]
看一下你的选择的地区

**Comment by byr1223** [comment]
额，选择的地区在哪看？

**Comment by zhouaini528** [comment]
你也可以选择，云服务器ECS    找到你的购买的服务器列表，列表傍边有远程连接   ，   然后按照教程走，   把安装代码复制或者输入进去，    可以不用DMS

**Comment by byr1223** [comment]
可以了，谢谢回复
