### ISSUE TITLE
连不上啊，请问有遇到这个问题吗

### ISSUE THREAD

**Issue by bigbigQI** [zhouaini528/scientific_internet_access#5]
按照你的教程做完以后，还是翻不出去，v2ray显示下面这个信息，请问直到这个问题怎么解决嘛

[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 47.56.182.191:63837: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 47.56.182.191:63837: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by zhouaini528** [comment]
我看你这里的端口是  63837    你是否按照教程里说的，把这个端口开放？  如果没开放  是无法连接的

**Comment by bigbigQI** [comment]
端口开放了，无法连接，下了个手机端试了下也无法连接，网上看有人也遇到这个问题，但没看到怎么解决

**Comment by zhouaini528** [comment]
你加我qq：465382251，github交流不是很方便。

**Comment by bigbigQI** [comment]
感谢

**Comment by DFAAQ** [comment]
我也遇到了這個問題，請問怎麽解決

**Comment by zhouaini528** [comment]
> 我也遇到了這個問題，請問怎麽解決
换其他区域多试试
